services:
  mssql:
    image: eventuateio/eventuate-mssql:$EVENTUATE_COMMON_VERSION
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: Eventuate123!
      ACCEPT_EULA: Y
      USE_DB_ID: ${USE_DB_ID}
      USE_JSON_PAYLOAD_AND_HEADERS: ${USE_JSON_PAYLOAD_AND_HEADERS}